#!/usr/bin/env python3
"""
把公开树里的 mt6785 gpufreq 旧头改造成"转发到 v1 mt6873 plat 头"的薄 shim.

背景 (mt6873 结构性问题):
  drivers/misc/mediatek/base/power/mt6785/mtk_gpufreq.h  (旧 mt6785 API, 94 行)
  drivers/misc/mediatek/base/power/include/gpufreq_v1/mt6873/mtk_gpufreq_plat.h (v1 真身, 186 行)

两个头各自用不同 include guard (_MT_GPUFREQ_H_ vs ___MT_GPUFREQ_PLAT_H___) 定义同名
struct/typedef/函数, 且 mt6785 旧头相对 v1:
  - 缺 18 个 extern 声明 (mt_gpufreq_get_shader_present / get_limit_user / bringup ...)
  - 缺全部 5 个 enum (mt_gpufreq_kicker[含 KIR_POLICY] / mt_power_state / mt_cg_state /
    mt_mtcmos_state / mt_buck_state) —— mt6785 头里一个 enum 都没有
  - mt_gpufreq_target 签名不兼容:
        mt6785: (unsigned int request_idx, bool is_real_idx)
        v1    : (unsigned int request_idx, enum mt_gpufreq_kicker)
    Mali 调用 mt_gpufreq_target(opp_idx, KIR_POLICY); 若按 mt6785 的 bool 声明编译,
    KIR_POLICY(=8) 会被隐式转成 true(=1)=KIR_PROC —— 静默的行为错误.

凡直接 #include mt6785 旧头的 .c (ged_kpi.c / Mali mtk_platform_common.c /
mali_kbase_gpuprops.c ...) 都会踩上述缺失, 逐个补声明是打地鼠. 这里做结构性修复:
让 mt6785 头只 #include v1 plat 头 => 全树只剩**唯一定义点**, 同时消除
"缺符号 / 缺 enum / 签名不一致 / 重复定义" 四类问题.

保留处理: mt6785 头里有 7 个 v1 plat 头没有的符号 (g_mfg_lock / power_control_enable /
disable / aee_rr_* ), 动态提取后原样保留, 避免引用它们的 TU 掉声明.

安全性:
  - v1 plat 头自带 guard ___MT_GPUFREQ_PLAT_H___, 任一 TU 同时经两条链拉入也只展开一次.
  - 不定义 _MT_GPUFREQ_H_ (上游 pristine plat 头不含该条件, 定义它反而可能误伤).
  - 原文件备份为 *.orig; 已 shim 过则跳过 (幂等).
  - mt6873 构建不编译 base/power/mt6785/*.c (MTK_PLATFORM=mt6873), 故改头不影响定义端.
  - 只改 base/power/mt6785/ 这一份 (已验证是 ged/Mali 的实际 include 目标),
    不动 eem_v2/mt6785/ 等其它同名副本.
"""
import os
import re
import sys

MARKER = "MTK_GPUFREQ_MT6785_FORWARD_SHIM"
PLAT_SUFFIX = os.path.join("include", "gpufreq_v1", "mt6873", "mtk_gpufreq_plat.h")
MT6785_SUFFIX = os.path.join("base", "power", "mt6785", "mtk_gpufreq.h")


def find_one(root, suffix):
    """在 root 下找路径以 suffix 结尾的文件, 返回第一个匹配."""
    suffix = suffix.replace("\\", "/")
    hits = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for fn in filenames:
            p = os.path.join(dirpath, fn).replace("\\", "/")
            if p.endswith(suffix):
                hits.append(p)
    hits.sort(key=len)
    return hits[0] if hits else None


def parse_externs(text):
    """提取顶层 extern 声明 (跨行拼到分号), 返回 [(符号名, 原文多行片段)]."""
    out = []
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        if lines[i].startswith("extern "):
            chunk = [lines[i]]
            while ";" not in "".join(chunk) and i + 1 < len(lines):
                i += 1
                chunk.append(lines[i])
            joined = "\n".join(chunk)
            flat = re.sub(r"\s+", " ", joined)
            m = re.search(r"(\w+)\s*\(", flat)
            name = m.group(1) if m else flat
            out.append((name, joined))
        i += 1
    return out


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."

    mt = find_one(root, MT6785_SUFFIX)
    if not mt:
        print("[gpufreq-shim] mt6785/mtk_gpufreq.h NOT FOUND -> skip (non-fatal)")
        return 0
    plat = find_one(root, PLAT_SUFFIX)
    if not plat:
        print("[gpufreq-shim] v1 plat header NOT FOUND -> skip (non-fatal)")
        return 0

    print("[gpufreq-shim] mt6785 header : %s" % mt)
    print("[gpufreq-shim] v1 plat header: %s" % plat)

    mt_text = open(mt, encoding="utf-8", errors="replace").read()
    if MARKER in mt_text:
        print("[gpufreq-shim] already shimmed -> skip (idempotent)")
        return 0
    plat_text = open(plat, encoding="utf-8", errors="replace").read()

    # v1 plat 头没有、只有 mt6785 才有的符号 -> 必须保留
    plat_names = {n for n, _ in parse_externs(plat_text)}
    keep = [src for n, src in parse_externs(mt_text) if n not in plat_names]
    print("[gpufreq-shim] preserving %d mt6785-only extern(s):" % len(keep))
    for n, src in parse_externs(mt_text):
        if n not in plat_names:
            print("               - %s" % n)

    # mt6785 头里的 #define (排除 include guard) 一并保留, 如 MT_GPUFREQ_SRAM_DEBUG
    defines = []
    for line in mt_text.split("\n"):
        s = line.strip()
        if s.startswith("#define ") and "_MT_GPUFREQ_H_" not in s:
            defines.append(s)
    if defines:
        print("[gpufreq-shim] preserving define(s): %s" % ", ".join(defines))

    # 从 mt6785 头所在目录到 plat 头的相对路径 (引号包含按包含者所在目录解析)
    rel = os.path.relpath(plat, os.path.dirname(mt)).replace("\\", "/")
    print("[gpufreq-shim] forward include -> \"%s\"" % rel)

    parts = [
        "/*",
        " * AUTO-GENERATED by flash/fix_gpufreq_mt6785_shim.py -- DO NOT EDIT.",
        " *",
        " * 原 mt6785 旧 gpufreq 头缺 18 个 extern / 全部 5 个 enum, 且 mt_gpufreq_target",
        " * 签名与 v1 不兼容 (bool vs enum mt_gpufreq_kicker). 此处改为直接转发到 v1 mt6873",
        " * plat 头, 使全树只有唯一定义点, 一次性消除缺符号/缺 enum/签名不一致/重复定义.",
        " * 原文件已备份为同目录 mtk_gpufreq.h.orig",
        " */",
        "",
        "#ifndef %s" % MARKER,
        "#define %s" % MARKER,
        "",
        "#include <linux/module.h>",
        "#include <linux/clk.h>",
        "#include <linux/mutex.h>",
        "#include <linux/types.h>",
        "",
        "/* 唯一定义点: v1 mt6873 plat 头 (enum / struct / 全部 extern) */",
        "#include \"%s\"" % rel,
        "",
    ]
    if defines:
        parts.append("/* 保留 mt6785 头原有 define */")
        parts.extend(defines)
        parts.append("")
    if keep:
        parts.append("/* 保留 v1 plat 头没有、仅 mt6785 头声明的符号 */")
        for src in keep:
            parts.append(src)
        parts.append("")
    parts.append("#endif /* %s */" % MARKER)
    parts.append("")

    open(mt + ".orig", "w", encoding="utf-8").write(mt_text)
    open(mt, "w", encoding="utf-8").write("\n".join(parts))
    print("[gpufreq-shim] rewrote %s (%d -> %d lines), backup at %s.orig"
          % (mt, mt_text.count("\n") + 1, len(parts), mt))
    return 0


if __name__ == "__main__":
    sys.exit(main())
